### PR TITLE
BAH-3475 | Use custom web.xml for oviyam2

### PR DESCRIPTION
**Pull request by mohan-13**
This PR removes the login prompt for Oviyam 2 when accessing DICOM files. This is done by unzipping the WAR and using a custom web.xml file with the following snippet commented.

```<!-- <security-constraint>
        <web-resource-collection>
            <web-resource-name>dispatcher</web-resource-name>
            <description>Only allows users with the role WebAdmin to access the Archive Web Administration pages</description>
            <url-pattern>*.jsp</url-pattern>
            <url-pattern>*.html</url-pattern>
            <url-pattern>*.do</url-pattern>
            <url-pattern>/oviyam</url-pattern>
            <http-method>GET</http-method>
            <http-method>POST</http-method>
        </web-resource-collection>
        <auth-constraint>
            <role-name>*</role-name>
        </auth-constraint>
    </security-constraint> -->
```

### CODE REVIEW

**Comment by gsluthra** [comment]
Seems fine to me. thanks!

**Comment by gsluthra** [comment]
Hopefully there is no security issue due to this?

**Comment by mohan-13** [comment]
This is how current versions of Bahmni (0.93) work. There is a security concern for Bahmni running on public instances where the DICOM image can be accessed if someone gets hold of the complete URL.

**Comment by gsluthra** [comment]
Should we add some information on the Bahmni Security Guide, WIKI regarding this, so people are aware on mitigations?

**Comment by mohan-13** [comment]
Yup, will add along with the steps to rebuild with authentication enabled if needed

**Pull request merged**
